# Server Configuration
server:
  port: 8085

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: Arun@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Microservice URLs
microservice:
  user-service:
    url: http://localhost:8081
  car-detail-service:
    url: http://localhost:8084