server:
  port: 8082

spring:
  application:
    name: sample-application
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_db
    username: root
    password: Arun@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configure multipart file upload size limits (if needed)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB